### ISSUE TITLE
Version of Rosserial

### ISSUE THREAD

**Issue by AlexisTM** [OpenAgInitiative/rosserial_arduino_libs#1]
Dear,

The different versions of Rosserial are generating different versions of the Arduino libs. Which version is this one?

**Comment by gordonbrander** [comment]
Hey there, I'm not sure I understand your question! Can you give me some more info?

**Comment by AlexisTM** [comment]
Hey, rosserial generate libraries. The libraries differ with the version of
Rosserial and the version ROS. Therefore, there should be the ROS version
and Rosserial version written somewhere

Le mar. 6 déc. 2016 19:47, Gordon Brander <notifications@github.com> a
écrit :

**Comment by gordonbrander** [comment]
Ah! @LeonChambers do you know what version of ROS/ROSSerial was used to generate this?

**Comment by LeonChambers** [comment]
It's ROS Indigo. I don't know what version of rosserial it is.

**Comment by LeonChambers** [comment]
Added this information to the README. It's rosserial 0.6.4 on ROS Indigo.
